#ifndef __psrfits_subband_cmd__
#define __psrfits_subband_cmd__
/*****
  command line parser interface -- generated by clig 
  (http://wsd.iitb.fhg.de/~geg/clighome/)

  The command line parser `clig':
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
*****/

typedef struct s_Cmdline {
  /***** -dm: Dispersion measure to use for the subband de-dispersion */
  char dmP;
  double dm;
  int dmC;
  /***** -nsub: Number of output frequency subbands */
  char nsubP;
  int nsub;
  int nsubC;
  /***** -dstime: Power-of-2 number of samples to average in time */
  char dstimeP;
  int dstime;
  int dstimeC;
  /***** -bytes: Make the raw data unsigned chars instead of signed shorts */
  char bytesP;
  /***** uninterpreted command line parameters */
  int argc;
  /*@null*/char **argv;
  /***** the whole command line concatenated */
  char *full_cmd_line;
} Cmdline;


extern char *Program;
extern void usage(void);
extern /*@shared*/Cmdline *parseCmdline(int argc, char **argv);

#endif

